### ISSUE TITLE
Access to a pokemon's pokedex description

### ISSUE THREAD

**Issue by fmonniot** [phalt/pokeapi#107]
Hi there !
First of all, thank you for this API!

I would want to know how I can get a pokemon description (as in the pokedex).
I have seen that `data/v2/csv/pokemon_species_flavor_text.csv` seems to have the data I look for but I can't find how to get _via_ the API.
Any idea ?

Thanks

**Comment by phalt** [comment]
@fmonniot have you tried the V1 API for this?

**Comment by fmonniot** [comment]
Well maybe I could (I haven't tried) but I would prefer not to use two
version of the API of I can.
I'm ready to open a PR if this is not currently implemented in V2 and if
needed

**Comment by phalt** [comment]
@fmonniot Let me ask @zaneadix if this is something we've merged into the project but not shipped yet :)

I need to get myself a weekend free so I can ship some recents changes :)

**Comment by nimaje** [comment]
At [data/v2/build.py line 1909 - 1918](https://github.com/phalt/pokeapi/blob/master/data/v2/build.py#L1909) the data goes in the db as `PokemonSpeciesFlavorText`.
I don't know if this is accessible trought the v2 api. I didn't find anything in the docs neighter online nor in the repo.

**Comment by zaneadix** [comment]
@phalt @fmonniot @nimaje So strange. I sincerely have no idea how I would have missed this. Working on implementing this right now.

**Comment by fmonniot** [comment]
@zaneadix No problem, I guess you are more interested in pokemon's statistics than in their description :)

**Comment by phalt** [comment]
Resolved in #111 - will let you know when it is shipped @fmonniot, then I can close this :)

**Comment by vihanggodbole** [comment]
Hey! Just a quick question - Any ETA on when will this be shipped?

**Comment by phalt** [comment]
@vihanggodbole my Sunday will be taken up mostly by shipping new things.

**Comment by vihanggodbole** [comment]
Since this is closed but I still can't find any description when I call the api on any pokemon, could you tell me how to access the description? Thanks!

**Comment by fleeting** [comment]
@vihanggodbole Thanks for that! I was also looking for the pokedex description with no luck until seeing your comment.

**Comment by zaneadix** [comment]
@fleeting @vihanggodbole You're looking for the `flavor_text_entries` param on the pokemon-species resource (NOT the pokemon resource). I'm seeing them pop up now thanks to @phalt 's work over the weekend :)

**Comment by fleeting** [comment]
Correct. I was looking everywhere else for it until @vihanggodbole's comment said it was in species. All good now.

**Comment by MaxHasADHD** [comment]
Could this be added to Pokemon instead? Would be nicer in the call. I also noticed that Pokemon has 811 results, white Pokemon Species only has 721 total results. It seems like a mess that I have to get all the pokemon, then all the species to get the description and evolutionary chain (something I also think should be included with the Pokemon entry)
